### ISSUE TITLE
adding transformers

### ISSUE THREAD

**Issue by antgr** [bentrevett/pytorch-nli#1]
Do you have any idea how could we use the transformers library to use bert pretrained model to boost the performance of this model?

**Comment by bentrevett** [comment]
I haven't looked into this yet, but it's definitely something I want to add in the future.

**Comment by bentrevett** [comment]
@antgr I have added a tutorial on how to use the `transformers` library to get a pre-trained BERT model for sentiment analysis. Hopefully it'll be useful starting point if you want to apply them to NLI.

https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/6%20-%20Transformers%20for%20Sentiment%20Analysis.ipynb

**Comment by antgr** [comment]
Thank you. I followed the same changes for nli
https://colab.research.google.com/drive/1QDc4K6rBXuVKtREPub6DdLij-z-jbLxo
but I have some errors to fix.
(I think that now are solved)
